 type User{
    name: String
    id: String
    email:String
        
  }
 extend type Query {
    getUser(id: ID!): [User]
  }
  type Status{
    statusCode: Int
    statusMessage: String
  }

  input InputUser{    
    name: String
    email: String 
  }   

 extend type Mutation{
    createUser(input: InputUser!): User! 
    updateUser(input: InputUser!): Status!
    deleteInUser(input: InputUser!): Status!
  }