 type User{
    name: String
    id: String
    email:String
        
  }
  type Query {
    getUser(id: ID!): [User]
    getOneUser(id: ID!): [User]
  }




  type Status{
    statusCode: Int
    statusMessage: String
  }

  input InputUser{ 
    id: String   
    name: String
    email: String 
  }   

  type Mutation{
    createUser(input: InputUser!): User! 
    updateUser(input: InputUser!): Status!
    deleteUser(input: InputUser!): Status!
  }
  